### ISSUE TITLE
Can't use AOT with double quotes in properties

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-aot#121]
### Actual Behaviour

Simple example to reproduce bug: I used micronaut-kfka with auth. My config:
```yaml
kafka:
  bootstrap:
    servers: localhost:9092
  sasl:
    mechanism: ''
    jaas:
      config: ${KAFKA_AUTH_SASL_MODULE:} required username="${KAFKA_USER:}" password="${KAFKA_PASS:}";
```

Next run `build` task and you will see in logs:
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.micronaut.aot.cli.Main.executeInIsolatedLoader(Main.java:113)
	at io.micronaut.aot.cli.Main.run(Main.java:87)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.micronaut.aot.cli.Main.execute(Main.java:134)
	at io.micronaut.aot.cli.Main.main(Main.java:138)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Caused by: java.lang.reflect.InvocationTargetException

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.micronaut.aot.cli.Main.executeInIsolatedLoader(Main.java:107)
	... 10 more
Caused by: java.lang.RuntimeException: Compilation errors:
File ApplicationStaticPropertySource.java, line: 25, ')' expected
File ApplicationStaticPropertySource.java, line: 25, ';' expected
File ApplicationStaticPropertySource.java, line: 25, illegal start of statement
File ApplicationStaticPropertySource.java, line: 25, not a statement
File ApplicationStaticPropertySource.java, line: 25, ';' expected
File ApplicationStaticPropertySource.java, line: 25, ';' expected
File ApplicationStaticPropertySource.java, line: 25, illegal start of statement
File ApplicationStaticPropertySource.java, line: 25, not a statement
File ApplicationStaticPropertySource.java, line: 25, ';' expected

	at io.micronaut.aot.MicronautAotOptimizer.throwCompilationError(MicronautAotOptimizer.java:240)
	at io.micronaut.aot.MicronautAotOptimizer.compileGeneratedSources(MicronautAotOptimizer.java:140)
	at io.micronaut.aot.MicronautAotOptimizer.access$200(MicronautAotOptimizer.java:98)
	at io.micronaut.aot.MicronautAotOptimizer$Runner.execute(MicronautAotOptimizer.java:344)
	at io.micronaut.aot.MicronautAotOptimizer.execute(MicronautAotOptimizer.java:202)
	... 15 more

Caused by: java.lang.RuntimeException: Compilation errors:

Execution failed for task ':prepareJitOptimizations'.
```

The same behavior with any properties with double quotes in application.yml

### Environment Information

 - Win11
 - JDK 11

### Version

3.5.3

**Comment by altro3** [comment]
Bug already fixed
