### ISSUE TITLE
`InvocationTargetException`: how to debug?

### ISSUE THREAD

**Issue by sgammon** [micronaut-projects/micronaut-aot#127]
### Expected Behavior

When adding Micronaut AOT to an existing application:

```kotlin
micronaut {
  version.set("3.7.0")
  runtime.set(io.micronaut.gradle.MicronautRuntime.NETTY)
  processing {
    incremental.set(true)
    annotations.addAll(listOf(
      "...",
    ))
  }
  aot {
    version.set("1.1.1")
    optimizeServiceLoading.set(true)
    convertYamlToJava.set(false)
    precomputeOperations.set(false)
    cacheEnvironment.set(false)
    optimizeClassLoading.set(false)
    optimizeNetty.set(false)
    deduceEnvironment.set(true)
  }
}
```

It should begin optimizing AOT without failing the build.

### Actual Behaviour

Error I am getting:
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at io.micronaut.aot.cli.Main.executeInIsolatedLoader(Main.java:113)
        at io.micronaut.aot.cli.Main.run(Main.java:87)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.micronaut.aot.cli.Main.execute(Main.java:134)
        at io.micronaut.aot.cli.Main.main(Main.java:138)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.micronaut.aot.cli.Main.executeInIsolatedLoader(Main.java:107)
        ... 10 more
Caused by: java.lang.RuntimeException: Compilation errors:
File unknown, line: -1, Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider io.micronaut.annotation.processing.TypeElementVisitorProcessor could not be instantiated

        at io.micronaut.aot.MicronautAotOptimizer.throwCompilationError(MicronautAotOptimizer.java:240)
        at io.micronaut.aot.MicronautAotOptimizer.compileGeneratedSources(MicronautAotOptimizer.java:140)
        at io.micronaut.aot.MicronautAotOptimizer.access$200(MicronautAotOptimizer.java:98)
        at io.micronaut.aot.MicronautAotOptimizer$Runner.execute(MicronautAotOptimizer.java:344)
        at io.micronaut.aot.MicronautAotOptimizer.execute(MicronautAotOptimizer.java:202)
        ... 15 more
```

### Steps To Reproduce

I'm not sure how to reproduce this yet, but with debug advice, I could determine those steps.

### Environment Information

- Operating System: macOS Monterey (12.6)
- Java 17 (GraalVM `22.x`)

### Version

3.7.0 (latest)

**Comment by melix** [comment]
Do you have a reproducer at hand?

**Comment by sgammon** [comment]
@melix i'm sorry, i don't -- the best i can share is the above. if you could share some advice about how to produce a better error, or attach a debugger during AOT's execution (I don't know much about what could be going wrong here), I'm happy to track it down and provide a reproduction repo.

**Comment by melix** [comment]
You can add this to your `build.gradle` file:

```gradle
tasks.withType(io.micronaut.gradle.aot.AbstractMicronautAotCliTask).configureEach {
    debug = true
}
```

**Comment by sgammon** [comment]
@melix it looks like, after some cajoling, this was an incompatibility with SLF4J 2.0. i haven't been able to catch the specific exception again to isolate it, but it's fixed now, and if i do catch it, i'll drop it here for context.

thank you for your help :)
