### ISSUE TITLE
Optimized nativeImage fails with flyway

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-aot#40]
### Expected Behavior

Optimized native image works. 

### Actual Behaviour

```
./gradlew :app:nativeOptimizedCompile

> Task :app:prepareNativeOptimizations
20:05:02.382 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [dev]
20:05:02.554 [main] INFO  i.m.aot.MicronautAotOptimizer - Detected environments: [dev]
20:05:02.676 [main] INFO  i.m.a.s.s.YamlPropertySourceGenerator - Converting application.yml into Java based configuration
20:05:02.683 [main] INFO  i.m.a.s.s.YamlPropertySourceGenerator - Converting application-dev.yml into Java based configuration
20:05:02.690 [ForkJoinPool.commonPool-worker-5] INFO  i.m.a.s.s.YamlPropertySourceGenerator - Converting application.yml into Java based configuration
20:05:02.693 [ForkJoinPool.commonPool-worker-5] INFO  i.m.a.s.s.YamlPropertySourceGenerator - Converting application-dev.yml into Java based configuration

> Task :app:nativeOptimizedCompile
[native-image-plugin] Using executable path: /Users/sdelamo/.sdkman/candidates/java/21.3.0.r17-grl/bin/native-image
[app:16653]    classlist:   1,805.81 ms,  0.94 GB
[app:16653]        (cap):   2,320.69 ms,  0.94 GB
[app:16653]        setup:   5,770.51 ms,  1.18 GB
[app:16653]     (clinit):   1,931.96 ms,  7.82 GB
[app:16653]   (typeflow):   6,346.67 ms,  7.82 GB
[app:16653]    (objects):  41,342.53 ms,  7.82 GB
[app:16653]   (features):  10,098.99 ms,  7.82 GB
[app:16653]     analysis:  63,860.40 ms,  7.82 GB
[app:16653]     universe:   4,612.64 ms,  7.82 GB
[app:16653]      (parse):   2,833.94 ms,  7.58 GB
[app:16653]     (inline):   6,060.04 ms,  6.64 GB
[app:16653]    (compile):  27,100.80 ms,  6.86 GB
[app:16653]      compile:  39,966.46 ms,  6.86 GB
[app:16653]        image:   5,164.13 ms,  6.88 GB
[app:16653]        write:   1,765.64 ms,  6.88 GB
[app:16653]      [total]: 123,177.00 ms,  6.88 GB
# Printing build artifacts to: /Users/sdelamo/github/micronaut-advocacy/micronaut-live-newsletter/app/build/native/nativeOptimizedCompile/app.build_artifacts.txt
[native-image-plugin] Native Image written to: /Users/sdelamo/github/micronaut-advocacy/micronaut-live-newsletter/app/build/native/nativeOptimizedCompile

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2m 16s
6 actionable tasks: 3 executed, 3 up-to-date
sdelamo@ig11 micronaut-live-newsletter % ./app/build/native/nativeOptimizedCompile/app 
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.2.3)

20:07:36.892 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [dev]
20:07:36.897 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
20:07:36.911 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
20:07:36.912 [main] INFO  i.m.flyway.AbstractFlywayMigration - Running migrations for database with qualifier [default]
20:07:36.915 [main] INFO  o.f.c.i.license.VersionPrinter - Flyway Community Edition 8.0.2 by Redgate
20:07:36.915 [main] INFO  o.f.c.i.d.base.BaseDatabaseType - Database: jdbc:postgresql://localhost:5432/postgres (PostgreSQL 11.5)
20:07:36.932 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Unable to obtain inputstream for resource: db/migration/V1__create-subscriber-table.sql
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Unable to obtain inputstream for resource: db/migration/V1__create-subscriber-table.sql
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1938)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:237)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3453)
	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3883)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:329)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:183)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
	at io.micronaut.live.Application.main(Application.java:39)
Caused by: org.flywaydb.core.api.FlywayException: Unable to obtain inputstream for resource: db/migration/V1__create-subscriber-table.sql
	at org.flywaydb.core.internal.resource.classpath.ClassPathResource.read(ClassPathResource.java:118)
	at org.flywaydb.core.internal.resolver.ChecksumCalculator.calculateChecksumForResource(ChecksumCalculator.java:64)
	at org.flywaydb.core.internal.resolver.ChecksumCalculator.calculate(ChecksumCalculator.java:43)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.getChecksumForLoadableResource(SqlMigrationResolver.java:123)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.addMigrations(SqlMigrationResolver.java:165)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:71)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:50)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.collectMigrations(CompositeMigrationResolver.java:107)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:90)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:83)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:41)
	at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:92)
	at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:153)
	at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:140)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
	at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:140)
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:380)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:53)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:126)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:121)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:208)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:121)
	at io.micronaut.flyway.AbstractFlywayMigration.runFlyway(AbstractFlywayMigration.java:100)
	at io.micronaut.flyway.AbstractFlywayMigration.forceRun(AbstractFlywayMigration.java:85)
	at io.micronaut.flyway.AbstractFlywayMigration.run(AbstractFlywayMigration.java:65)
	at io.micronaut.flyway.DataSourceMigrationRunner.lambda$null$0(DataSourceMigrationRunner.java:65)
	at java.util.Optional.ifPresent(Optional.java:178)
	at io.micronaut.flyway.DataSourceMigrationRunner.lambda$onCreated$1(DataSourceMigrationRunner.java:63)
	at java.util.Optional.ifPresent(Optional.java:178)
	at io.micronaut.flyway.DataSourceMigrationRunner.onCreated(DataSourceMigrationRunner.java:60)
	at io.micronaut.flyway.DataSourceMigrationRunner.onCreated(DataSourceMigrationRunner.java:37)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2393)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2653)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1932)
	... 7 common frames omitted
```

### Steps To Reproduce

Clone [micronaut-advocacy/micronaut-live-newsletter aot branch](https://github.com/micronaut-advocacy/micronaut-live-newsletter/tree/aot). 

Open one terminal and run PostgreSQL: 

```
docker run -it --rm -p 5432:5432 -e POSTGRES_USER=dbuser -e POSTGRES_PASSWORD=theSecretPassword -e POSTGRES_DB=postgres postgres:11.5-alpine
```

Open another terminal: 

```
 export DATASOURCES_DEFAULT_USERNAME=dbuser 
export DATASOURCES_DEFAULT_PASSWORD=theSecretPassword
./gradlew :app:nativeOptimizedCompile
./app/build/native/nativeOptimizedCompile/app 

```

### Environment Information

Note it works with regular native image. 

```
./gradlew :app:nativeCompile 
./app/build/native/nativeCompile/app      
```

### Example Application

https://github.com/micronaut-advocacy/micronaut-live-newsletter

### Version

3.2.3

**Comment by melix** [comment]
mmm, are you using `1.0.0-M4` ?

**Comment by melix** [comment]
Actually this is https://github.com/graalvm/native-build-tools/pull/182 which will require the GraalVM plugin 0.9.9 which should be out this week.

**Comment by sdelamo** [comment]
> Actually this is [graalvm/native-build-tools#182](https://github.com/graalvm/native-build-tools/pull/182) which will require the GraalVM plugin 0.9.9 which should be out this week.

I added the `awaiting-third-party` flag. I assume this will require a new release of Micronaut Application plugin?

**Comment by melix** [comment]
> I assume this will require a new release of Micronaut Application plugin?

Correct, so if you want to squeeze some doco changes ;)
