### ISSUE TITLE
liquibase.xml is added twice to a classpath while optimizedRun

### ISSUE THREAD

**Issue by message** [micronaut-projects/micronaut-aot#43]
### Actual Behaviour

```
Caused by: java.io.IOException: Found 2 files that match classpath:liquibase/liquibase.xml: jar:file:/home/message/www/liquibase-aot/build/libs/liquibaseaot-0.1-jit.jar!/liquibase/liquibase.xml, file:/home/message/www/liquibase-aot/build/resources/main/liquibase/liquibase.xml
        at liquibase.resource.AbstractResourceAccessor.openStream(AbstractResourceAccessor.java:25)
        at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:50)
```

### Example Application

https://github.com/message/micronaut-liquibase-aot

### Version

3.2.3

**Comment by message** [comment]
Example application also covers #41

**Comment by melix** [comment]
This is probably to be fixed in the Gradle plugin. Error occurs when running `optimizedRun`.
